name: Docker Image CI

on:
  push:
    tags:
      - v*


jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USER }}/httpod
      GH_IMAGE_NAME: ghcr.io/tgunsch/httpod

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --target slim --tag $GH_IMAGE_NAME:${GITHUB_REF:10}-slim
        docker tag $GH_IMAGE_NAME:${GITHUB_REF:10}-slim $GH_IMAGE_NAME:latest-slim
        docker build . --file Dockerfile --target ubuntu --tag $GH_IMAGE_NAME:${GITHUB_REF:10}
        docker tag $GH_IMAGE_NAME:${GITHUB_REF:10} $GH_IMAGE_NAME:latest
    - name: Log into gh registry
      run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u tgunsch --password-stdin
    - name: Push image to gh registry
      run: |
        docker push $GH_IMAGE_NAME:${GITHUB_REF:10}-slim
        docker push $GH_IMAGE_NAME:latest-slim
        docker push $GH_IMAGE_NAME:${GITHUB_REF:10}
        docker push $GH_IMAGE_NAME:latest
